### ISSUE TITLE
 Has Many Relation - delete items

### ISSUE THREAD

**Issue by marena** [mootensai/yii2-relation-trait#10]
Hi,

I use yii2-relation-trait with genreated CRUD by Gii (with your yii2-enhanced-gii)
I have Has Many relation. For example orders and order items.

So: I have saved Order with one or more order items. 
If there is at least one order item. It works fine. If not, relation save is skipped.It looks like saveAll function gets full relatedRecors to this relation. So code in if (!empty($this->relatedRecords)) {  is processed

Marek

**Comment by mootensai** [comment]
Please update, I've tried and it works..
