### ISSUE TITLE
Composite Primary Key

### ISSUE THREAD

**Issue by lupoalberto** [mootensai/yii2-relation-trait#15]
Hi
I try to use relation trait for this table:

> CREATE TABLE `test` (
  `table1id` bigint(20) NOT NULL,
  `table2id` bigint(20) NOT NULL,
  `field1` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`table1id`,`table2id`),
  KEY `key1_id_fk` (`table1id`),
  CONSTRAINT `key1_id_fk` FOREIGN KEY (`table1id`) REFERENCES `table1` (`id`),
  CONSTRAINT `key2_id_fk` FOREIGN KEY (`table2id`) REFERENCES `table2` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1

as you can see I'm trying to use a composite primary key without an "id" column. I don't know if this is an issue, since if I change the name of my 'table1id' column into 'id' everything works fine. My problem is, that I have to change all my database schema (not only one column ;-) ) and before doing that I preferred asking you if there is a way to fix that.

**Comment by mootensai** [comment]
It shouldn't be any problem. I usually use tablexx_id for foreign key column.. It's strange..

**Comment by lupoalberto** [comment]
Hmm...very strange. Is there a need for an underscore? I get the following error message:

> Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause'
The SQL being executed was: SELECT * FROM `test` WHERE `id`=1

> Error
> Info:
> Array
> 
> (
>     [0] => 42S22
>     [1] => 1054
>     [2] => Unknown column 'id' in 'where clause'
> )
> 
> ↵
> Caused by: PDOException
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause'

**Comment by mootensai** [comment]
That's because your table don't have any primary key. I think I haven't support that yet.. 
I don't know if Yii support that table when you use your model..
My tables always use primary key even for junction table..

**Comment by lupoalberto** [comment]
No. My table has a Primary Key! As you can see in my first post, the table "test" has primary key: 

> PRIMARY KEY (table1id,table2id),

**Comment by mootensai** [comment]
Oh, sorry.. I miss that.. this is the sample of my junction table 
```
CREATE TABLE `proyek_mesin` (
	`id` VARCHAR(32) NOT NULL,
	`mesin_id` INT(11) NOT NULL DEFAULT '0',
	`proyek_id` INT(11) NOT NULL DEFAULT '0',
	`ip` VARCHAR(16) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `mesin_id` (`mesin_id`),
	INDEX `proyek_id` (`proyek_id`),
	CONSTRAINT `proyek_mesin_ibfk_1` FOREIGN KEY (`mesin_id`) REFERENCES `mesin` (`id`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `proyek_mesin_ibfk_2` FOREIGN KEY (`proyek_id`) REFERENCES `proyek` (`id`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```

Sorry, I'm currently busy right now, so I can't fix it soon enough. If you want to fix it right now, maybe you could restructure your tables.. 

I'm terribly sorry if it really bothers you / inconvenient to you.

I'll keep this issue open to remind me..

**Comment by lupoalberto** [comment]
Ok. So there is no other workaround to "bypass" the issue, right?
When do you think you can fix it? Just approximately...is it a few weeks? months? I hope not years! ( :-D )

**Comment by mootensai** [comment]
I don't really know.. hopefully weeks.. :laughing:

**Comment by lupoalberto** [comment]
Thank you so far. Don't forget me! :blush:

**Comment by mootensai** [comment]
Hi! Now I have time to fix this.
I run your SQL but it says 
`errno: 150 "Foreign key constraint is incorrectly formed"`

what DB did you use?

**Comment by mootensai** [comment]
I've build your sql, and it's working fine. How to reproduce the error? Where should I create? at table1 or at test?

**Comment by lupoalberto** [comment]
Table is test. 
Here is what I did:
- import the database in mysql
- go to yii2/web/index.php?r=gii
- put * into gemerator IO for table name (model and CRUD)
- then I went to yii2/web/index.php?r=persons/index
- created a new person, related 2 countries and 2 languages
- saved
- went back to update the created person
- removed both countries (left both languages) and saved
- got automatically redirected to views page. The removed countries are still there...

**Comment by lupoalberto** [comment]
I have to appologize, I forgot to tell you, that the problem occures only if I try to use it in an other view file. 
To reproduce the error just import my test database (see attached file)
[test_composite.sql.zip](https://github.com/mootensai/yii2-relation-trait/files/309084/test_composite.sql.zip)
If you try to create models and CRUD with gii and then go to index.php?r=exercises/index just try to create a new "exercise". Put something into title and try to add some tags (like tag1 and tag2). Then just try to save it and you'll get the error I already posted above in my second comment.

**Comment by mootensai** [comment]
Thanks!
