### ISSUE TITLE
getRelationData conflicts with user defined methods

### ISSUE THREAD

**Issue by obalsoy** [mootensai/yii2-relation-trait#16]
First of all, you are doing a great job. Keep up the good work.

I have a problem with methods I add to model classes. getRelationData calls all the methods in a model and it conflicts with those I add.

Looks like you added a try-catch with no statement "//if method name can't be call" to prevent issues, but if a user-defined method throws an exception, it stops the execution where you don't expect it to stop. 

You need to find a way to skip user defined methods without an attempt to call them. User methods may doing exhaustive calculations or db calls. Your method makes unnecessary calls.

Maybe one way would be to let developers to start their methods with certain way, like adding 'my' or 'user', etc., in the front. 

Another way would be to let people add methods to their models while getRelationData only looks for methods in its base class or a parent class.

I will solve this temporarily by checking a prefix of mine, which will be a problem in the next update.

Thanks.

**Comment by mootensai** [comment]
what do you think about this ?
```
if (strpos($method->name, 'get' ) === false){
  continue;
}
```

if not contain 'get' then I'll skip it

**Comment by obalsoy** [comment]
Initially, I thought you were calling only getXXX() methods. Then, noticed
that you were calling all.

I think that makes sense.

Ozgur


---
Ozgur Balsoy
216-255-7188

**Comment by mootensai** [comment]
fixed by last commit 

forgot to close it 

https://github.com/mootensai/yii2-relation-trait/commit/63af1a65457f3d33a5a32d556b42538953a87c1a
