### ISSUE TITLE
Using Enhanced Yii2 Gii - no relation

### ISSUE THREAD

**Issue by Koncar93** [mootensai/yii2-relation-trait#19]
Hi,

I have simple table in database:

CREATE TABLE Document
(
	DocumentID            INTEGER NULL,
	Title				  VARCHAR(50),
        Published			  DATE
);

ALTER TABLE Document ADD  PRIMARY KEY (DocumentID);

I created model and CRUD, but when I try to create new Document I'm getting error:
Invalid Parameter – yii\base\InvalidParamException
app\models\Document has no relation named "published-document-published".
Caused by: Unknown Method – yii\base\UnknownMethodException
Calling unknown method: app\models\Document::getpublished-document-published()

Please help me, I'm getting this error only when I have Date field in database.

**Comment by mootensai** [comment]
Add your attribute to skipped relation when save/load.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the 3 Indonesia network.

**Comment by Koncar93** [comment]
I tried to add Published in skipped relations in CRUD generator but it's still same. Do I have to make some changes directly in code?

**Comment by mootensai** [comment]
Please send me your schema.. I'll try it later

**Comment by Koncar93** [comment]
I have only one table in my database.

CREATE TABLE Document
(
DocumentID INTEGER NULL,
Title VARCHAR(50),
Published DATE
);

ALTER TABLE Document ADD PRIMARY KEY (DocumentID)

**Comment by rufushoffmann** [comment]
Got same problem. Only on fields using Kartiks DateControl.
![datecreate](https://cloud.githubusercontent.com/assets/18526375/16557055/db464e42-41dd-11e6-9484-22c43dc21b8e.jpg)

**Comment by mootensai** [comment]
Whoops, suddenly I got something to do, and not bring my laptop with me. I will fix it on Wednesday.

**Comment by mootensai** [comment]
Thanks! Please try again by updating this package! :grin:

**Comment by ruffiction** [comment]
Still doesnt work for me. Same error. 
But already thanks for trying fix it.

**Comment by mootensai** [comment]
Wait, I'll re-check..

**Comment by Koncar93** [comment]
Still same error...

**Comment by altairdeark** [comment]
@mootensai Last update is not workable:
`PHP Fatal Error – yii\base\ErrorException
Call to a member function load() on null`

`$relObj = (empty($value[$relPKAttr[0]])) ? new $relModelClass : $relModelClass::findOne($value[$relPKAttr[0]]);`
`$relObj->load($value, '');`
`$this->populateRelation($relName, $relObj);`

Waiting new updates

**Comment by mootensai** [comment]
Ok, I'll fix this issue by this week..                                                                                                                                                                                  ‎

**Comment by ruffiction** [comment]
Next step in our project will be CRUDs. So i hope you'll fix at as soon as able.
Already thanks for this powerful generator.

**Comment by mootensai** [comment]
I'll fix it as soon as possible. Thank you for using this extension and for reporting this error everyone!

**Comment by mootensai** [comment]
Please try again.. I've test it, and it works.. Thanks everyone!

@altairdeark : which line is that??

**Comment by ruffiction** [comment]
Still got same error. Will some infos about Yiiversion or something be helpful for you?
![enhanced](https://cloud.githubusercontent.com/assets/18526375/16684747/05e5e604-4507-11e6-8847-5054c924e192.jpg)

**Comment by mootensai** [comment]
Have you run 'composer update'?From your error it shows RelationTrait line 31, The new code line 31 is no 'getRelation($relName)‎'

**Comment by ruffiction** [comment]
Yes i did. On no relation tables it works fine now for me but not on tables with relations. Now the relations didnt works fine looks like. Wanna Chat or Email to find a solution?
![enhanced2](https://cloud.githubusercontent.com/assets/18526375/16685985/18c9cb8e-450f-11e6-86c5-442e0996b0b1.jpg)

**Comment by mootensai** [comment]
Can you send your schema?

**Comment by ruffiction** [comment]
Wrote u in chat.

**Comment by mootensai** [comment]
ruffiction's problem is not related to this issue..
