### ISSUE TITLE
Multiple n:m in one form

### ISSUE THREAD

**Issue by lupoalberto** [mootensai/yii2-relation-trait#22]
Hello mootensai

I unfortunately think I found another mistake. In the attached example I have 4 tables: main (the main table), sub1 (first n:m relation), sub2 (second n:m relation), persons (the target table of the n:m relations).
All the models, controller and views I created with IO Generator of gii and leaved them untouched.

Now if you try to go the main view in yii2 everything works fine, as long as I put in values for only one subquery. At the moment I try to put in values for subquery1 and subquery2 it fails with this error message:

> SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 3 column(s)
> The SQL being executed was: DELETE FROM `sub2` WHERE (`mainid`=1) AND ((mainid, personsid, somevalue) NOT IN (('1','1'), ('1','2'), ('1','3'), ('1','2','23')))
> [example.sql.zip](https://github.com/mootensai/yii2-relation-trait/files/434186/example.sql.zip)

What do you mean with "What function do you use?"? The error occures when put values in both subForms an try to save the main form. As said before, it works perfectly as long as I leave one of the subForms empty.

**Comment by mootensai** [comment]
Yes, this extension is not support for "through" relation (relation of children). Sorry
