### ISSUE TITLE
after validation on new related, return model with id

### ISSUE THREAD

**Issue by markux** [mootensai/yii2-relation-trait#25]
Hi,

I 've a simple main form, with a tabular form: I add two new rows: Document 1 not valid and Document 2 valid.

After submit I see the correct validation message "Document #1 : Percentage cannot be blank. ", BUT Document 2 has an id value setted! Then after new submit I got an exception on RelationTrait line 71, because $relObj is null ( $relModelClass::findOne($relPost[$relPKAttr[0]]); return null because id is setted, but it not exist on db)

thanks

**Comment by mootensai** [comment]
about line 71 is already fixed.

about the first question, how is Document 1 & Document 2 related?

**Comment by mootensai** [comment]
I've found the problem. It's because you're not using innodb as your engine. 
Maybe you're using MyISAM as your db engine as it's not support transaction.
