### ISSUE TITLE
yii2-dynamicform - Delete Relation

### ISSUE THREAD

**Issue by newerton** [mootensai/yii2-relation-trait#27]
What treatment do I use when all relations are removed from Dynamic Form?

Whenever I remove all items from Dynamic Form, it returns again, and I see in the database the primary ID of the related table, it remains the same.

**Comment by mootensai** [comment]
could you send me your schema dump?

**Comment by mootensai** [comment]
I haven't tried with Dynamic Form. I'll close this issue as you're not responding.

If this issue still happening, please contact me again..
