### ISSUE TITLE
File uploading problem in related models

### ISSUE THREAD

**Issue by razzaghis** [mootensai/yii2-relation-trait#28]
Hi,

I 've two model. The first model(Subject) has two fields: id, title and the second model(Files) has three fields: id, subject_id, file_name.
After submitting I see this validation message: "Files #1: Please upload a file.", but I Select a file to upload. I set form enctype field to 'multipart/form-data'.
Is there any solution to solve this problem?
thanks

**Comment by mootensai** [comment]
I use this widget
http://demos.krajee.com/widget-details/fileinput
https://github.com/kartik-v/yii2-widget-fileinput
I use that like this
```
<?= $form->field($model, 'image_path')->widget(FileInput::className(),[
        'model' => $model,
        'attribute' => 'image_path',
        'options' => [
            'placeholder' => 'Gambar',
            'data-show-preview' => false
        ],
        'pluginOptions' => [
            'showPreview' => true,
            'showUpload' => false,
            'allowedFileExtensions' => ['jpg', 'png'],
            'maxFileSize' => 12 * 1024
        ]
    ]);
    ?>
```
