### ISSUE TITLE
Issue if there is more than one realtion in one table

### ISSUE THREAD

**Issue by lupoalberto** [mootensai/yii2-relation-trait#34]
Hi mootensai

don't know if you remember me? We talked about some issues some time ago and you fixed them all, except one. The title of this thread should explain everything, so, if I have more than one relation in my table, updating fails, because you don't "reset" the $fields array for every relation. The problem only occures if the related tables have different names of their key columns. I fixed that bug in my local version by adding this to line 104 in your RelationTrait.php file:
`$fields = [];` 
Could you please verify that and eventually add it too, so I don't have to edit the file manually after your updates.

Thanks for the great work!

**Comment by mootensai** [comment]
Thanks! It should be fixed now..
