### ISSUE TITLE
Relation records empty after main entity insert

### ISSUE THREAD

**Issue by nariman924** [mootensai/yii2-relation-trait#37]
Hi I have an issue on trying to create record. Then I found what on 

    public function saveAll($skippedRelations = [])
    {
        /* @var $this ActiveRecord */
        $db = $this->getDb();
        $trans = $db->beginTransaction();
        $isNewRecord = $this->isNewRecord;
        try {
            if ($this->save()) {
                $error = false;
                if (!empty($this->relatedRecords)) {
 - relatedRecords - is empty if  main entity inserting, on update everything OK. Sorry my eng. pls

**Comment by mootensai** [comment]
if relatedRecord is empty, then maybe you're not populating the relation data on your model..
I've tried, and no problem to me..
Please explain more to reopen this issue.

**Comment by mootensai** [comment]
please use stable version and not the dev-master version
