### ISSUE TITLE
Wrong bracket

### ISSUE THREAD

**Issue by Patricy** [mootensai/yii2-relation-trait#44]
Hi.

Great job, man! I saved a lot of time with this trait

I has some problem with one-to-one relatios and found small bug. Check please:

ELSE statement for one-to-one relation (line202) belong to wrong IF. Now it's for  **if (!empty($records))**(127)
but should be for **if ($AQ->multiple)**(132)

Way to fix:
- move closing bracket from line 200 to line 217

**Comment by mootensai** [comment]
Thanks!
