### ISSUE TITLE
loadAll() returns false if no relation in post()

### ISSUE THREAD

**Issue by matthiasrust** [mootensai/yii2-relation-trait#47]
If post data contains only flat attributes loadAll() returns false!

It returned true before 1.1.7.

**Comment by mootensai** [comment]
could you give me a sample POST array?

**Comment by kidzen** [comment]
same here... 
It retun false because relation is not filled..

**Comment by mootensai** [comment]
Please give me an Array sample

**Comment by kidzen** [comment]
![capture](https://user-images.githubusercontent.com/14084511/31108193-4493242a-a82a-11e7-9d64-7c851f5d0ce4.PNG)

**Comment by kidzen** [comment]
```php
    public function loadAll($POST, $skippedRelations = [])
    {
        if ($this->load($POST)) {
            $shortName = StringHelper::basename(get_class($this));
            $relData = $this->getRelationData();
            foreach ($POST as $model => $attr) {
                if (is_array($attr)) {
                    if ($model == $shortName) {
                        foreach ($attr as $relName => $relAttr) {
var_dump($POST);
var_dump($attr);
die;
//here where the function fail since $relAttr is an array but not a relation
                            if (is_array($relAttr)) {
                                $isHasMany = !ArrayHelper::isAssociative($relAttr);
                                if (in_array($relName, $skippedRelations) || !array_key_exists($relName, $relData)) {
                                    continue;
                                }

                                return $this->loadToRelation($isHasMany, $relName, $relAttr);
                            }
//here you should handle where to save if no relation were filled
                            // return true;
                        }
                    } else {
                        $isHasMany = is_array($attr) && is_array(current($attr));
                        $relName = ($isHasMany) ? lcfirst(Inflector::pluralize($model)) : lcfirst($model);
                        if (in_array($relName, $skippedRelations) || !array_key_exists($relName, $relData)) {
                            continue;
                        }

                        return $this->loadToRelation($isHasMany, $relName, $attr);
                    }
                }
            }
        }
        return false;
    }
```

**Comment by kidzen** [comment]
```php
  public function loadAll($POST, $skippedRelations = [])
    {
        if ($this->load($POST)) {
            $shortName = StringHelper::basename(get_class($this));
            $relData = $this->getRelationData();
            foreach ($POST as $model => $attr) {
                if (is_array($attr)) {
                    if ($model == $shortName) {
                        foreach ($attr as $relName => $relAttr) {
var_dump($POST);
var_dump($attr);
die;
//here where the function fail since $relAttr is an array but not a relation
                            if (is_array($relAttr)) {
                                $isHasMany = !ArrayHelper::isAssociative($relAttr);
                                if (in_array($relName, $skippedRelations) || !array_key_exists($relName, $relData)) {
                                    continue;
                                }

                                return $this->loadToRelation($isHasMany, $relName, $relAttr);
                            }
//here you should handle where to save if no relation were filled
                            // return true; //by returning true here seems valid..but please recheck if i miss anything
                        }
                    } else {
                        $isHasMany = is_array($attr) && is_array(current($attr));
                        $relName = ($isHasMany) ? lcfirst(Inflector::pluralize($model)) : lcfirst($model);
                        if (in_array($relName, $skippedRelations) || !array_key_exists($relName, $relData)) {
                            continue;
                        }

                        return $this->loadToRelation($isHasMany, $relName, $attr);
                    }
                }
            }
        }
        return false;
    }
```

**Comment by mootensai** [comment]
which array is not loaded? Contract array should be loaded right? Maybe `awarded_date-contract-awarded_date-disp` array not loaded? Or is it Contract array also not loaded?

**Comment by mootensai** [comment]
@kidzen problem is different than @matthiasrust 

@matthiasrust is valid, @kidzen need to re-confirm

@matthiasrust I need your Array sample

**Comment by a10317** [comment]
Hi,
I have the same problem. In your former versionsof loadAll there was a "return true" also.
Greetings

**Comment by kidzen** [comment]
The problem is not on data not get loaded..
my contract has 3 other hasMany relation attached to it..
the data get loaded succesfully, but if i leave the relation form empty, it wont return true..

**Comment by Lordfef** [comment]
same issue. After update, loadAll return false on create/update. If i use "load" instead of "loadAll" it works.
But before the update, same code, same table, "loadAll" works fine.

**Comment by mootensai** [comment]
may i get your POST array sample @Lordfef

**Comment by mootensai** [comment]
Please try again..

**Comment by Lordfef** [comment]
i run "composer update" but there's no update for this repo.

Next a simple table that works before last release

MODEL:
`<?php

namespace common\models\db\base;

use Yii;

/**
 * This is the base model class for table "mag_causali".
 *
 * @property integer $id
 * @property string $nome
 * @property string $segno
 *
 * @property \common\models\db\MagMov[] $magMovs
 */
class MagCausali extends \yii\db\ActiveRecord
{
    use \mootensai\relation\RelationTrait;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nome'], 'string', 'max' => 45],
            [['segno'], 'string', 'max' => 1]
        ];
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mag_causali';
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nome' => 'Nome',
            'segno' => 'Segno',
        ];
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMagMovs()
    {
        return $this->hasMany(\common\models\db\MagMov::className(), ['id_cau' => 'id']);
    }
    }
`
CONTROLLER:
`
    /**
     * Creates a new MagCausali model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MagCausali();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
`
$_POST:
`Array (
[_csrf-backend] => vV0binF5STbOYr4ozCClGDRtWmPmBVIB1BmWq1KbRrEwjHYdvVu___Qs_PORm3S1d1mkQYmNdw9wq7eJ8jo62Q==
[MagCausali] => Array (
[id] =>
[nome] => test
[segno] => +
)
) `

**Comment by mootensai** [comment]
change your composer to dev-master or on terminal 
`$ composer require 'mootensai/yii2-relation-trait:dev-master'`

**Comment by Lordfef** [comment]
Must i regenerate Model and Crud with yii-enhanced?

**Comment by mootensai** [comment]
no need..

**Comment by Lordfef** [comment]
Well. I do different test.
I can say the problem "loadAll" now is OK. Goog work, thank's.

I ask you if must i regenerate model and crud, because, after the creation success, the controller load the view, and the view give the error:
`Invalid Configuration – yii\base\InvalidConfigException
Please specify the "model" property.`
I know it's another issue.
But i see that in the view file generated from gii-enhanced there is a control for the first GridView of relations with if($providerRELATION->totalCount){.... , but the control is missing after for the DetailView of relations.

**Comment by a10317** [comment]
LoadAll - error is fixed – everything works 
Thank you for your efforts

**Comment by brian3t** [comment]
Thanks for the fix. 
Please mark this fix as a release, otherwise many people will encounter this same error.

Great job.

**Comment by mootensai** [comment]
Done! Thanks @brian3t
