### ISSUE TITLE
Too few arguments to function app\models\base\Dokter::getListDokterRS(), 0 passed and exactly 1 expected

### ISSUE THREAD

**Issue by moysoft** [mootensai/yii2-relation-trait#49]
Hi mootensai, i had problem when update the date. The error is quite strange.

 in C:\xampp\htdocs\mcs3x\models\base\Dokter.php at line 126

            
        'updatedByAttribute' => 'updated_by',
            ],
          ];
    }
 
    public function getListDokterRS($rs_id)
    {
        $data = Yii::$app->db->createCommand(
            'SELECT t_dokter.nama_dokter, t_dokter.kode_dokter
                FROM t_dokter_poli
                INNER JOIN t_dokter ON t_dokter_poli.kode_dokter = t_dokter.kode_dokter
                WHERE kode_poli in (SELECT kode_poli from t_poli WHERE kode_rs = :kode_rs)')
            ->bindValue(':kode_rs', $rs_id)
            ->queryAll();
 
2. app\models\base\Dokter::getListDokterRS()
3. in C:\xampp\htdocs\mcs3x\vendor\mootensai\yii2-relation-trait\RelationTrait.php at line 417 – 
                   call_user_func([app\models\Dokter, 'getListDokterRS'])
                     
                            continue;
                }
                if (strpos($method->name, 'get') !== 0) {
                    continue;
                }
                try {
                    $rel = call_user_func(array($this, $method->name));
                    if ($rel instanceof ActiveQuery) {
                        $name = lcfirst(preg_replace('/^get/', '', $method->name));
                        $stack[$name]['name'] = lcfirst(preg_replace('/^get/', '', $method->name));
                        $stack[$name]['method'] = $method->name;
                        $stack[$name]['ismultiple'] = $rel->multiple;
                        $stack[$name]['modelClass'] = $rel->modelClass;
4. in C:\xampp\htdocs\mcs3x\vendor\mootensai\yii2-relation-trait\RelationTrait.php at line 43 – app\models\base\Dokter::getRelationData()

**Comment by mootensai** [comment]
Please try again..

**Comment by moysoft** [comment]
What do you mean with "Please try again..", what's wrong?? Should I update the component?

**Comment by moysoft** [comment]
After updated the component with composer the error is still in there. Still error and not working.

**Comment by mootensai** [comment]
please try again with dev-master version

**Comment by moysoft** [comment]
Thank you it works now
