### ISSUE TITLE
Clean your code from debug messages

### ISSUE THREAD

**Issue by bashibozuk** [mootensai/yii2-relation-trait#5]
There must not be any debug messages in a "library" . you sholud remove all **echo**, **var_dump**, etc. You can use Yii::trace() , which will make your messages appear in the yii 2 debug bar

**Comment by mootensai** [comment]
ok, sorry i've fix that, please use dev release instead

**Comment by mootensai** [comment]
i've re-release this extension. it should be okay to use stable release by now
