### ISSUE TITLE
This extension is pure shit and should be deleted !!!

### ISSUE THREAD

**Issue by Ziggizag** [mootensai/yii2-relation-trait#67]
This extension rape through all methods prefixed with "get" and abuse them. This method clears link table records and creates new - effectively messing in more complex relations. This is pure VIRUS and the author should be ashamed!

**Comment by mootensai** [comment]
How so? could you explain what you did and show the Model that use it?

**Comment by Ziggizag** [comment]
Models are complex with many relations.

But your overall code is piece of shit. 

First of all - not each and every instance of ActiveQuery is a relation!!!

Looka at your code - first of all - you effectively rip through all "get" queries here:

try {
          $rel = call_user_func(array($this, $method->name));
          if ($rel instanceof ActiveQuery) {
              $name = lcfirst(preg_replace('/^get/', '', $method->name));
              $stack[$name]['name'] = lcfirst(preg_replace('/^get/', '', $method->name));
              $stack[$name]['method'] = $method->name;
              $stack[$name]['ismultiple'] = $rel->multiple;
              $stack[$name]['modelClass'] = $rel->modelClass;
              $stack[$name]['link'] = $rel->link;
              $stack[$name]['via'] = $rel->via;
         }
} catch (ErrorException $exc) {

then - you fuck delete all records as a madman:

if (!$isNewRecord) {
	//DELETE WITH 'NOT IN' PK MODEL & REL MODEL
	if ($isManyMany) {
		// Many Many
		$query = ['and', $notDeletedFK];
		foreach ($notDeletedPK as $attr => $value) {
			$notIn = ['not in', $attr, $value];
			array_push($query, $notIn);
		}
		try {
			$relModel->deleteAll($query);
		} catch (IntegrityException $exc) {
			$this->addError($name, "Data can't be deleted because it's still used by another data.");
			$error = true;
		}
	} else {
		// Has Many
		$query = ['and', $notDeletedFK, ['not in', $relPKAttr[0], $notDeletedPK]];
		if (!empty($notDeletedPK)) {
			try {
				$relModel->deleteAll($query);
			} catch (IntegrityException $exc) {
				$this->addError($name, "Data can't be deleted because it's still used by another data.");
				$error = true;
			}
		}
	}
}

You are a criminal - your fucking plugin nearly killed my database!
