### ISSUE TITLE
Deleting records on "Update"

### ISSUE THREAD

**Issue by borishalter** [mootensai/yii2-relation-trait#7]
Hi, since 1.0.9 updating a record results in deleting the record and records in related tables, too.
This behavior came with 1.0.9, older releases (e.g. 1.0.8) works as expected.

For details pls. see the Yii forum:
http://www.yiiframework.com/forum/index.php/topic/69824-weird-behavior-with-yii2-relation-trait/page__pid__296328#entry296328

Regards, Boris

**Comment by mootensai** [comment]
Sorry, will check it right away..

**Comment by mootensai** [comment]
It's strange, even if it's going to 'no children left', your model is not new record, so it shouldn't run any command. Could you show me the debug/log when you update? Especially the SQLs

**Comment by mootensai** [comment]
which database you're using? Is it MySQL?

**Comment by mootensai** [comment]
Fixed it! Please try @dev version. Sorry about this.

**Comment by borishalter** [comment]
﻿Hi Yohanes,

 
Version 1.1.1 works as expetced.

 
Thank you for your great work, this will boost my development.

 
Regards,

Boris



-----Ursprüngliche Nachricht-----
Von: Yohanes Candrajaya <notifications@github.com>
Gesendet: Fre 26 Februar 2016 06:20
An: mootensai/yii2-relation-trait <yii2-relation-trait@noreply.github.com>
CC: Boris Halter <boris.halter@servsystems.de>
Betreff: Re: [yii2-relation-trait] Deleting records on "Update" (#7)

Fixed it! Please try @dev version. Sorry about this.

—
Reply to this email directly or view it on GitHub.

 

-- 
This email was Virus checked by UTM 9. http://www.sophos.com


-- 
This email was Virus checked by UTM 9. http://www.sophos.com

**Comment by mootensai** [comment]
You're welcome! :smile:
