### ISSUE TITLE
Using Enhanced Yii2 Gii CRUD with skipped relations

### ISSUE THREAD

**Issue by marena** [mootensai/yii2-relation-trait#8]
(sory for my poor english)

Hi,
dont know if its bug, or just I dont get it right.

I generate model and CRUD files with mootensai/yii2-enhanced-gii. In gii CRUD form I skip some relations. Then after update form submit all related rows are deleted. Controller dint get skipped relation data in POST and saveAll delete all related rows (RelationTrait:197)

My scenario:
I create some orders with client "asdasd", then I go to client update (generated with skipeed relations: orders) and confirm form. All orders for client "asdasd" will be deleted.

Is that right or I miss something?

Thanks for answer

sql:
`SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `client`;
CREATE TABLE `client` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_group_id` int(11) DEFAULT NULL,
  `type` enum('retail','wholesale') NOT NULL,
  `payment_method` enum('cache','transfer') NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text,
  `address` varchar(128) DEFAULT NULL,
  `phone` varchar(128) DEFAULT NULL,
  `email` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_group_id` (`client_group_id`),
  CONSTRAINT `client_ibfk_3` FOREIGN KEY (`client_group_id`) REFERENCES `client_group` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `client` (`id`, `client_group_id`, `type`, `payment_method`, `name`, `description`, `address`, `phone`, `email`) VALUES
(14,	19,	'retail',	'cache',	'asdasd',	'',	'',	'',	''),
(15,	19,	'wholesale',	'cache',	'test 2',	'',	'',	'',	'');

DROP TABLE IF EXISTS `client_group`;
CREATE TABLE `client_group` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `client_group` (`id`, `name`) VALUES
(19,	'Cenik pro frajera');

DROP TABLE IF EXISTS `order`;
CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) DEFAULT NULL,
  `order_status_id` int(11) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `date_ordered` datetime DEFAULT NULL,
  `date_to_deliver` datetime DEFAULT NULL,
  `date_shipped` datetime DEFAULT NULL,
  `date_completed` datetime DEFAULT NULL,
  `date_tax` datetime DEFAULT NULL,
  `price_total` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `order_status_id` (`order_status_id`),
  CONSTRAINT `order_ibfk_3` FOREIGN KEY (`order_status_id`) REFERENCES `order_status` (`id`),
  CONSTRAINT `order_ibfk_4` FOREIGN KEY (`client_id`) REFERENCES `client` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `order_status`;
CREATE TABLE `order_status` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) NOT NULL,
  `color` varchar(32) DEFAULT NULL,
  `paid` tinyint(1) NOT NULL DEFAULT '0',
  `shipped` tinyint(1) NOT NULL DEFAULT '0',
  `delivered` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `order_status` (`id`, `name`, `color`, `paid`, `shipped`, `delivered`) VALUES
(1,	'New',	'red',	0,	0,	0),
(3,	'Delivered',	'',	0,	0,	0);

-- 2016-04-21 17:31:29`

**Comment by marena** [comment]
Hi,

I made quick modification. I add into function loadAll() second parameter - $relations = []. This parameter says what relation to save / delete. Its safer for me, to include allowed relation, then skipped relations. 

`    public function loadAll($POST, $relations = [])
    {
            ...
            foreach ($POST as $key => $value) {
                if ($key != $shortName && strpos($key, '_') === false) {
                ...
                    if (!in_array($relName, $relations))
                        continue;

                    if ($isManyMany) {
`

Now I need to modify generator to add non skipped relations into controller loadAll funtion

**Comment by marena** [comment]
Forget to close Issue

**Comment by mootensai** [comment]
Thanks! This is a good idea, although people still need to manually insert the arguments. But this will do for a while.

**Comment by mootensai** [comment]
I'll reopen this issue to remind me to fix it on the future update

**Comment by marena** [comment]
Yes. But I think its better to add argument maualy (or gii do this for you), then lost all related rows.
But its just quick and dirty modification. Now I have some problem to delete last row with many many relation.

**Comment by mootensai** [comment]
Please create another issue for your many-many relation issue.

**Comment by mootensai** [comment]
HI, could you show me the code of your saveAll(array $skippedRelations) function?

**Comment by marena** [comment]
Hi, sure, but sory - its quick fix. Nothing fancy

```
public function saveAll($relations = [])
    {

        try {
            if ($this->save()) {
                $error = 0;
                if (!empty($this->relatedRecords)) {
                    foreach ($this->relatedRecords as $name => $records) {

                        if (!in_array($name, $relations))
                            continue;
                     ...
                } else {
                    //No Children left
                        ...
                        foreach ($relData as $rel) {
                             if (!in_array($rel['name'], $relations))
                                 continue;
                                 ...
                        }
                }
}
```

**Comment by mootensai** [comment]
Thanks! How about your many-many relations issue? Is it fixed? How you fix it?

**Comment by marena** [comment]
Posted right now as new issue... examaple is Has Many relation, but I think its same issue.
